### ISSUE TITLE
Dodać animacje

### ISSUE THREAD

**Issue by sbstnkr** [sbstnkr/sportsnewsapp#11]
Poprawienie UX za pomocą biblioteki Animate.css

**Comment by sbstnkr** [comment]
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/44314400/79071095-0b265e00-7cda-11ea-9e9f-47c4e5af7b87.gif)

Co sądzicie o takim udogodnieniu? @anialusz @karolina011

**Comment by sbstnkr** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44314400/79071770-cef4fc80-7cdd-11ea-96c8-ed2bcd81bbf2.gif)

Co sądzicie o takim udogodnieniu? @anialusz @karolina011

**Comment by anialusz** [comment]
Fajny pomysł, możemy dodać taka animację

**Comment by sbstnkr** [comment]
animacje dodane
