### ISSUE TITLE
Prawidłowe wyświetlanie się elementów

### ISSUE THREAD

**Issue by sbstnkr** [sbstnkr/sportsnewsapp#17]
Read button powinien się pojawiać tylko wtedy kiedy jest rzeczywiście mniej tekstu; część o zawodnikach i nadchodzących wydarzeniach powinna się wyświetlać tylko wtedy kiedy te informacje są dostępne. Jeśli chodzi o część z podstawowymi danymi to trzeba postąpić analogicznie plus w przypadku gdy rok założenia wynosi '0', tez tej informacji nie wyświetlać.

![gif](https://user-images.githubusercontent.com/44314400/79114128-cd314480-7d82-11ea-8ad5-8f8f958318a3.gif)

**Comment by anialusz** [comment]
wszystko działa ok
