### ISSUE TITLE
Team Section - zmienić format godziny 

### ISSUE THREAD

**Issue by karolina011** [sbstnkr/sportsnewsapp#3]
![image](https://user-images.githubusercontent.com/54043002/78503126-efb0d580-7764-11ea-85bb-a1590f2f9e42.png)
Zmienić format godziny przy coming events, żeby było bez sekund

**Comment by anialusz** [comment]
Sprawdziłam format zwracanej godziny, wszystkie sprawdzone przeze mnie wartości godziny przy coming events są w formacie HH:MM:SS.
Jeżeli nie ma żadnego wyjątku od tej reguły można usunąć ostanie trzy znaki używając substring()/slice().

**Comment by anialusz** [comment]
Działa w porzadku.

![obraz](https://user-images.githubusercontent.com/36817931/79647530-8d1df780-81b0-11ea-936d-34584274fec2.png)
