### ISSUE TITLE
Nie pojawia sie informacja o zawodniku po kliknięciu (przy niektorych zespolach)

### ISSUE THREAD

**Issue by anialusz** [sbstnkr/sportsnewsapp#35]
Przyklad:
Po wyszukaniu USA/Baseball/Boston Red Sox i kliknięciu w konkretnego zawodnika nie pojawia się informacja o nim

![obraz](https://user-images.githubusercontent.com/36817931/79643644-44604180-81a4-11ea-8069-fff47302d76c.png)

**Comment by anialusz** [comment]
Wyświetlanie zawodników działa w porządku

**Comment by anialusz** [comment]
Znalazłam jeszcze kilka zapytań przy których nadal nie działa wyświetlanie informacji o zawodniku.
Przykłady:
![obraz](https://user-images.githubusercontent.com/36817931/79851094-258cc580-83c5-11ea-9161-3aad33533a60.png)
![obraz](https://user-images.githubusercontent.com/36817931/79851108-2a517980-83c5-11ea-810c-ad6db8a3077f.png)
![obraz](https://user-images.githubusercontent.com/36817931/79851121-2e7d9700-83c5-11ea-8787-47636ad02b88.png)

**Comment by karolina011** [comment]
Jest okej, zamykam
