### ISSUE TITLE
Alert odnośnie braku danej dyscypliny - zle wyswietlanie przy zmianie kraju

### ISSUE THREAD

**Issue by anialusz** [sbstnkr/sportsnewsapp#36]
Przykład:
Na  początek wyszukujemy np. USA/Baseball/Boston Red Sox klikamy Search, a następnie zmieniamy kraj na Greece. 

Alert wyskakuje od razu po zmianie kraju, nie dając możliwości zmiany dyscypliny sportowej.

**Comment by sbstnkr** [comment]
poprawione, @karolina011 @anialusz sprawdzicie?

**Comment by karolina011** [comment]
Jest ok, @anialusz sprawdź jeszcze u siebie.

**Comment by anialusz** [comment]
Działa w porządku
