### ISSUE TITLE
Brak opisu druzyny - nic nie zostaje wyświetlone

### ISSUE THREAD

**Issue by anialusz** [sbstnkr/sportsnewsapp#44]
Znalazłam kilka zespołów które da się wyszukać u nas w programie i które są w API, ale nie posiadają żadnego opisu, w związku z tym nic się nie dzieje po kliknięciu przycisku Search. 

Co myślicie żeby obsługiwać taką sytuacje? 
Można dodać do alertu sprawdzanie czy selectedTeam.strDescriptionEN jest nullem, albo dodać po prostu informacje w miejscu opisu zespołu typu "Obecnie nie posiadamy opisu zespołu".

Macie jakieś pomysły jak można rozwiązać tą sytuacje? 

Przykłady zapytań: 
![obraz](https://user-images.githubusercontent.com/36817931/79854311-8d450f80-83c9-11ea-92b9-d2a81ac13a00.png)
![obraz](https://user-images.githubusercontent.com/36817931/79854338-96ce7780-83c9-11ea-8bef-c497a1e66805.png)

**Comment by karolina011** [comment]
Tak, zdecydowanie trzeba taką informację dorobić. Wydaje mi się, że lepiej to będzie zrobić w alercie, a Wy co myślicie?

**Comment by karolina011** [comment]
Może zróbmy to na ifie że jeśli nie istnieje opis zespołu lub zawodnicy i strona nie jest ładowana pierwszy raz to wyświetlmy, ten alert? 
![image](https://user-images.githubusercontent.com/54043002/80308755-016c2280-87d1-11ea-85b5-07123c321a2b.png)

**Comment by anialusz** [comment]
Właśnie przetestowałam tą sytuacje i alert jednak nie jest najlepszą opcją według mnie. Bo np te dwa zapytania które wrzuciłam na początku nie mają opisu teamu, ale juz np. mają logo teamu, czy swój przypisany kraj, wiec można wtedy wyświetlić tak dane:  
![obraz](https://user-images.githubusercontent.com/36817931/80308720-b94d0000-87d0-11ea-85f9-e2077c1e19ef.png)
![obraz](https://user-images.githubusercontent.com/36817931/80308765-121c9880-87d1-11ea-8927-6fda73b2b88c.png)

A jeśli damy alert to ignorujemy te dane (logo, kraj, itp)

**Comment by sbstnkr** [comment]
Tak, tutaj rozwiązaniem będzie dodanie v-if="selectedTeam.strDescriptionEN || selectedTeam.strTeamBanner" w team description section

**Comment by anialusz** [comment]
Tak jak ustaliliśmy na spotkaniu - będziemy wyświetlać dane które udostępnia API.

**Comment by karolina011** [comment]
Działa tak jak ustalaliśmy, zamykam issue.
