### ISSUE TITLE
News API - brak obrazków do newsów

### ISSUE THREAD

**Issue by anialusz** [sbstnkr/sportsnewsapp#46]
Nie wiem czy to chwilowa przerwa po stronie API z newsami, ale nie udostępnia aktualnie w ogóle urlToImage dla newsów. 

Aktualny stan karuzeli z newsami: 
![obraz](https://user-images.githubusercontent.com/36817931/80308340-c36dff00-87ce-11ea-9e34-8e43287f4b10.png)

Dodam obsługę takiej sytuacji - domyślny obrazek dla wszystkich newsów.

**Comment by karolina011** [comment]
Defaultowy obrazek jest ok, zamykam
