### ISSUE TITLE
Karuzela z newsami - gdzie umieścić

### ISSUE THREAD

**Issue by anialusz** [sbstnkr/sportsnewsapp#5]
Która opcja karuzeli z newsami według was bardziej pasuje do wyglądu strony? 

Aktualnie jest dodana do repozytorium opcja 2 - karuzela na dole strony.

Opcja 1 - karuzela na samej górze strony:
![karuzela2](https://user-images.githubusercontent.com/36817931/78568458-6fe94080-7822-11ea-8f6a-480f5974e136.png)

Opcja 2 - karuzela na dole strony:
![karuzela1](https://user-images.githubusercontent.com/36817931/78568453-6eb81380-7822-11ea-9121-e61e84c7c0e6.png)

**Comment by sbstnkr** [comment]
@anialusz ja również jestem za opcja na dole

**Comment by anialusz** [comment]
Zgodnie uznaliśmy ze karuzela wygląda lepiej na dole strony.
