### ISSUE TITLE
Dodanie biblioteki Animate on Scroll

### ISSUE THREAD

**Issue by sbstnkr** [sbstnkr/sportsnewsapp#51]
Co myślicie o takim rozwiązaniu?
https://michalsnik.github.io/aos/

![Apr-26-2020 19-01-30](https://user-images.githubusercontent.com/44314400/80314230-9e8a8380-87f0-11ea-8691-0ffee7589979.gif)

**Comment by sbstnkr** [comment]
@anialusz @karolina011

**Comment by karolina011** [comment]
Jak dla mnie wygląda fajnie.

**Comment by anialusz** [comment]
Zgadzam sie z Karoliną, fajnie wygląda. Można dodać tą bibioteke

**Comment by sbstnkr** [comment]
biblioteka dodana, awaiting test

**Comment by karolina011** [comment]
Działa dobrze, zamykam issue.
