### ISSUE TITLE
Tooltip - odstępy

### ISSUE THREAD

**Issue by karolina011** [sbstnkr/sportsnewsapp#53]
Gdy nie ma baneru zespołu, tooltip zachodzi na opis zespołu, a że ma lekko przezroczyste tło, to tekst staje się mało przejrzysty.
może przesuńmy go nad ikonę i może trochę zmniejszmy szerokość, tak do szerokości tła sekcji? @anialusz , @sbstnkr - co myślicie?
![image](https://user-images.githubusercontent.com/54043002/80631638-52407d00-8a56-11ea-9d58-e40c13c294b3.png)

**Comment by anialusz** [comment]
Dobry pomysł, wtedy nie powinien zasłaniać żadnych informacji

**Comment by sbstnkr** [comment]
naprawione, dzięki za sugestię, dodaje tag awaiting test

**Comment by karolina011** [comment]
Teraz jest ok, zamykam issue.
