### ISSUE TITLE
Nie pojawiające się detale artykułu kiedy nie ma contentu

### ISSUE THREAD

**Issue by sbstnkr** [sbstnkr/sportsnewsapp#58]
<img width="240" alt="Screenshot 2020-04-30 at 21 51 35" src="https://user-images.githubusercontent.com/44314400/80753102-fd236a80-8b2c-11ea-8183-d3c9dba9a6a8.png">

Zauważyłem teraz, że w takim przypadku po kliknięciu w artykuł nic się nie dzieje. 
Moją propozycją jest dodanie v-if="newsToShow.content" w tagu <p>
i dodatkowo zrobiłbym to samo dla newsToShow.description

**Comment by anialusz** [comment]
Zamknęłam przez przypadek. 
Sprawdźcie proszę czy teraz wszystko działa, aktualnie 18-sty news z polski ma ten problem :)

**Comment by sbstnkr** [comment]
wszystko działa, zamykam
