### ISSUE TITLE
Brakująca przerwa pomiędzy Team Info a Coming Events

### ISSUE THREAD

**Issue by anialusz** [sbstnkr/sportsnewsapp#61]
Brakuje odstępu w wypadku gdy v-card Team Info jest odrazu nad v-cardem Events

Przykład: 
![obraz](https://user-images.githubusercontent.com/36817931/80799222-8a56d580-8ba6-11ea-836c-b68bb8022c93.png)
![obraz](https://user-images.githubusercontent.com/36817931/80799208-81660400-8ba6-11ea-842e-29fa8ae6dcb3.png)

**Comment by sbstnkr** [comment]
okey, działa zamykam
