### ISSUE TITLE
Za długi tekst zostaje wyświetlony odnośnie opisu sportu

### ISSUE THREAD

**Issue by anialusz** [sbstnkr/sportsnewsapp#66]
Przy niektórych sportach (np. hokej) opis sportu po kliknięciu w tooltip jest bardzo długi. Przy testowaniu aplikacji na telefonie zajmuje on całą stronę. 

Trzeba ograniczyć ilość wyświetlanego tekstu.

**Comment by karolina011** [comment]
Teraz jest ok, zamykam issue.
